# baser sur la derniere version ubuntu
FROM ubuntu:latest
# Mettre a jour apt en utilisant :
RUN apt-get update
# mettre a niveau les logiciels actuel installer via apt en utilisant:
RUN apt-get upgrade -y
#Une fois fais, vs pouvez executer l'image docker ds un conteneur et elle fera echo a "hello world!" sur le terminal
CMD [ "echo", "Hello World!"]
