# Utilise l'image officielle de Nginx
FROM nginx:latest
# Copie ton fichier de configuration Nginx dans le dossier de conf de Nginx
COPY default.conf /etc/nginx/conf.d/default.conf
# Expose le port 80
EXPOSE 80
